"""
ploidy_pipeline.py
==================

A small, self-contained ploidy pipeline for fluorescence images of
multinucleate cells. It does the same core thing as iSPy (the collaborator's
tool) - classify each nucleus into a ploidy level from its fluorescence
intensity using a Gaussian Mixture Model - and then adds the one extra step
iSPy does not do for you: comparing the nuclei *within the same cell* to see
whether a cell's nuclei share a ploidy or not.

It is written to be readable if you are rusty with Python. Every block is
commented. You do not edit this file to use it - you pass your settings on the
command line (see the examples at the bottom of this docstring).

WHAT GOES IN
------------
A CSV where each row is ONE NUCLEUS, with at least:
  * an intensity column  (summed fluorescence = proxy for DNA = proxy for ploidy)
  * a cell-id column     (which parent cell the nucleus belongs to)
Optionally:
  * a volume column      (nuclear size - an independent check on ploidy)
  * a group/sample column (e.g. plant or genotype) to keep runs separate
  * a 'true_ploidy' column (only the demo data has this; used for validation)

WHAT COMES OUT  (all written into an output folder, default: example_outputs/)
-------------------------------------------------------------------------
  per_nucleus_classified.csv  your input + a 'ploidy_class' (1..K) and
                              'ploidy_label' (2C, 4C, ...) column per nucleus
  per_cell_summary.csv        one row per cell: how many nuclei, which ploidy
                              levels it contains, and whether it is uniform/mixed
  summary.txt                 a plain-text report of every headline number
  fig1_intensity_gmm.png      intensity histogram + the fitted ploidy peaks
  fig2_model_selection.png    BIC/AIC vs number of peaks (how K was chosen)
  fig3_class_percentages.png  % of nuclei at each ploidy level
  fig4_within_cell.png        THE key figure: do nuclei within a cell match?
  fig5_intensity_vs_volume.png  2D sanity check, points colored by ploidy class
  fig6_validation.png         (only if a true_ploidy column exists)

THE METHOD, IN ONE PARAGRAPH
----------------------------
DNA content doubles at each ploidy step (2C -> 4C -> 8C ...), and fluorescence
is proportional to DNA content. So if you take log-base-2 of intensity, the
ploidy levels become a row of evenly spaced bumps. A Gaussian Mixture Model
fits K bell curves to those bumps; each bell curve is one ploidy class. We let
the data choose K using the BIC score, then sort the classes from dimmest to
brightest and label them 1..K (class 1 = lowest ploidy). The fold-change
between neighbouring class means should come out near 2.0 if these really are
ploidy doublings - the pipeline prints that number so you can check.

EXAMPLES
--------
  # 1) Just run the built-in demo (after: python3 make_demo_data.py)
  python3 ploidy_pipeline.py

  # 2) Your own data, letting BIC choose the number of ploidy levels
  python3 ploidy_pipeline.py --csv data/my_nuclei.csv \
      --intensity-col Total_Intensity --cell-col Cell_ID \
      --volume-col Nuclear_Volume

  # 3) Force exactly 4 ploidy classes and call the lowest one 2C
  python3 ploidy_pipeline.py --csv data/my_nuclei.csv \
      --intensity-col Total_Intensity --cell-col Cell_ID \
      --n-classes 4 --base-ploidy 2
"""

import argparse
import os
import sys
import textwrap

import numpy as np
import pandas as pd

# Use a non-interactive plotting backend so figures save to disk without
# needing a screen. Must be set before importing pyplot.
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.mixture import GaussianMixture

# A colorblind-friendly qualitative palette (Paul Tol), the same family iSPy
# uses. Class 1 gets the first color, class 2 the second, and so on.
PALETTE = ["#4477AA", "#EE6677", "#228833", "#CCBB44",
           "#66CCEE", "#AA3377", "#BBBBBB", "#000000",
           "#882255", "#44AA99"]


# ---------------------------------------------------------------------------
# 1. Command-line options
# ---------------------------------------------------------------------------
def parse_args():
    p = argparse.ArgumentParser(
        description="Classify nuclear ploidy from fluorescence and compare "
                    "nuclei within each cell.",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--csv", default="data/demo_nuclei.csv",
                   help="Input CSV, one row per nucleus "
                        "(default: data/demo_nuclei.csv)")
    p.add_argument("--intensity-col", default="Total_Intensity",
                   help="Column holding summed fluorescence per nucleus.")
    p.add_argument("--cell-col", default="Cell_ID",
                   help="Column identifying the parent cell of each nucleus. "
                        "Use 'none' if every nucleus is its own cell.")
    p.add_argument("--volume-col", default="Nuclear_Volume",
                   help="Optional nuclear-size column (use 'none' to skip).")
    p.add_argument("--group-col", default="none",
                   help="Optional column to analyse groups separately "
                        "(e.g. genotype). 'none' = pool everything.")
    p.add_argument("--n-classes", type=int, default=0,
                   help="Force this many ploidy classes. 0 = let BIC choose.")
    p.add_argument("--min-classes", type=int, default=1,
                   help="Smallest number of classes to try when auto-choosing.")
    p.add_argument("--max-classes", type=int, default=8,
                   help="Largest number of classes to try when auto-choosing.")
    p.add_argument("--base-ploidy", type=int, default=2,
                   help="Ploidy of the dimmest class, for labelling (2 => 2C).")
    p.add_argument("--label", default="fluorescence intensity",
                   help="Name of the measured quantity, used on figure axes/titles "
                        "(e.g. 'nuclear size' for a size-based run).")
    p.add_argument("--mixed-fold-threshold", type=float, default=1.5,
                   help="A cell is only called 'confidently mixed' if its "
                        "brightest nucleus is at least this many times brighter "
                        "than its dimmest. 1.5 sits between no-doubling (1x) and "
                        "a full doubling (2x), so it ignores within-class noise.")
    p.add_argument("--outdir", default="example_outputs",
                   help="Folder to write figures and tables into.")
    p.add_argument("--seed", type=int, default=0,
                   help="Random seed (keeps results reproducible).")
    return p.parse_args()


# ---------------------------------------------------------------------------
# 2. Load and sanity-check the data
# ---------------------------------------------------------------------------
def load_data(args):
    if not os.path.exists(args.csv):
        sys.exit(f"ERROR: input file not found: {args.csv}\n"
                 f"Tip: run `python3 make_demo_data.py` first to create the demo.")

    # Most CSVs are comma-separated, but some European tools (and ilastik in
    # some locales) use semicolons. Try comma, fall back to semicolon.
    df = pd.read_csv(args.csv)
    if df.shape[1] == 1:
        df = pd.read_csv(args.csv, sep=";")

    if args.intensity_col not in df.columns:
        sys.exit(f"ERROR: intensity column '{args.intensity_col}' not in CSV.\n"
                 f"Columns found: {list(df.columns)}\n"
                 f"Set the right one with --intensity-col.")

    # Drop rows with missing or non-positive intensity (can't take log of those).
    n0 = len(df)
    df = df[df[args.intensity_col].notna()]
    df = df[df[args.intensity_col] > 0].copy()
    if len(df) < n0:
        print(f"  note: dropped {n0 - len(df)} rows with missing/<=0 intensity")

    # If there is no real cell column, make every nucleus its own cell so the
    # rest of the code still runs (the within-cell figure just won't be useful).
    if args.cell_col.lower() == "none" or args.cell_col not in df.columns:
        if args.cell_col.lower() != "none":
            print(f"  note: cell column '{args.cell_col}' not found - treating "
                  f"each nucleus as its own cell (no within-cell comparison).")
        args.cell_col = "_cell_id_auto"
        df[args.cell_col] = np.arange(1, len(df) + 1)

    return df


# ---------------------------------------------------------------------------
# 3. The ploidy model: fit Gaussian mixture on log2(intensity)
# ---------------------------------------------------------------------------
def fit_ploidy_gmm(intensity, args):
    """
    Fit a Gaussian Mixture Model to log2(intensity) and return everything we
    need to describe and plot the ploidy classes.

    Returns a dict with:
      k            chosen number of classes
      class_id     array, the ploidy class (1..k) for each input nucleus
      means_log2   sorted class means in log2 space (low -> high)
      fold_change  ratio between neighbouring class means in real units (~2 hoped)
      Ns, bic, aic the model-selection curves (for the BIC/AIC figure)
      x_log2       the log2-transformed intensities (handy for plotting)
    """
    # The single most important line: move to log-2 space, where ploidy
    # doublings become equal steps. reshape(-1, 1) makes it a column, which is
    # the shape scikit-learn expects.
    x_log2 = np.log2(np.asarray(intensity, dtype=float)).reshape(-1, 1)

    # Decide which numbers of classes (K) to consider.
    if args.n_classes and args.n_classes > 0:
        candidate_Ns = [args.n_classes]          # user forced a specific K
    else:
        hi = min(args.max_classes, len(x_log2))  # never ask for more classes than points
        candidate_Ns = list(range(args.min_classes, hi + 1))

    Ns, bic, aic, models = [], [], [], []
    for n in candidate_Ns:
        gmm = GaussianMixture(
            n_components=n,
            covariance_type="full",   # in 1D all covariance types are equivalent
            n_init=10,                # restart 10x and keep the best fit (stability)
            max_iter=500,
            random_state=args.seed,
        ).fit(x_log2)
        Ns.append(n)
        bic.append(gmm.bic(x_log2))  # Bayesian Information Criterion: lower = better
        aic.append(gmm.aic(x_log2))  # Akaike Information Criterion: lower = better
        models.append(gmm)

    # Pick the model with the smallest BIC (this is "let the data choose K").
    best = int(np.argmin(bic))
    gmm = models[best]
    k = Ns[best]

    # gmm.predict gives each nucleus a component number, but those numbers are
    # in arbitrary order. We re-rank them by their mean so that class 1 is
    # always the dimmest (lowest ploidy) and class k the brightest.
    raw_labels = gmm.predict(x_log2)
    means = gmm.means_.ravel()
    order = np.argsort(means)                 # raw component indices, dim -> bright
    rank_of_raw = np.empty(k, dtype=int)
    rank_of_raw[order] = np.arange(1, k + 1)  # map raw component -> class 1..k
    class_id = rank_of_raw[raw_labels]

    means_log2 = np.sort(means)               # class means, log2 space, ascending
    means_real = 2.0 ** means_log2            # the same means back in real units
    fold_change = means_real[1:] / means_real[:-1]   # neighbour ratios (~2 hoped)

    return dict(k=k, class_id=class_id, means_log2=means_log2,
                means_real=means_real, fold_change=fold_change,
                Ns=np.array(Ns), bic=np.array(bic), aic=np.array(aic),
                x_log2=x_log2.ravel(), gmm=gmm, order=order)


def ploidy_label(class_id, base_ploidy):
    """Turn class number 1,2,3,... into a ploidy label '2C','4C','8C',...

    Assumes each class up is one DNA doubling (the thing fold_change checks).
    """
    return f"{base_ploidy * (2 ** (class_id - 1))}C"


# ---------------------------------------------------------------------------
# 4. Within-cell analysis: do the nuclei inside one cell share a ploidy?
# ---------------------------------------------------------------------------
def within_cell_analysis(df, cell_col, intensity_col, fold_threshold=1.5):
    """
    Build one row per cell describing its nuclei, and return that table plus a
    few headline numbers.

    Two ways of calling a cell 'mixed':
      is_mixed            its nuclei landed in more than one ploidy CLASS. Simple
                          and matches iSPy, but a tiny bit jumpy: a nucleus that
                          sits right on a class boundary can flip a truly uniform
                          cell to 'mixed' just from measurement noise.
      is_mixed_confident  the above AND the brightest nucleus is >= fold_threshold
                          times the dimmest. This ignores within-class wobble and
                          only flags cells with a real intensity gap. Report THIS
                          one as your headline; report is_mixed for completeness.

    We also keep intensity_fold_range (brightest/dimmest), a model-free,
    threshold-free number: uniform cells sit near 1, real doublings near 2+.
    """
    records = []
    for cell, sub in df.groupby(cell_col):
        classes = sub["ploidy_class"].to_numpy()
        inten = sub[intensity_col].to_numpy()
        distinct = np.unique(classes)
        fold_range = float(inten.max() / inten.min())
        records.append({
            cell_col: cell,
            "n_nuclei": len(sub),
            "n_distinct_ploidy": len(distinct),
            "min_class": int(classes.min()),
            "max_class": int(classes.max()),
            "class_spread": int(classes.max() - classes.min()),
            "is_mixed": len(distinct) > 1,
            "is_mixed_confident": (len(distinct) > 1) and (fold_range >= fold_threshold),
            "ploidy_labels": ",".join(sorted(set(sub["ploidy_label"]))),
            "intensity_fold_range": fold_range,
        })
    per_cell = pd.DataFrame(records)

    multi = per_cell[per_cell["n_nuclei"] >= 2]   # only multinucleate cells count
    headline = {
        "n_cells": len(per_cell),
        "n_multinucleate": len(multi),
        "n_mixed": int(multi["is_mixed"].sum()),
        "pct_mixed": (100.0 * multi["is_mixed"].mean()) if len(multi) else 0.0,
        "n_mixed_confident": int(multi["is_mixed_confident"].sum()),
        "pct_mixed_confident": (100.0 * multi["is_mixed_confident"].mean()) if len(multi) else 0.0,
        "fold_threshold": fold_threshold,
        "median_fold_uniform": float(
            multi.loc[~multi["is_mixed"], "intensity_fold_range"].median())
            if (~multi["is_mixed"]).any() else float("nan"),
        "median_fold_mixed": float(
            multi.loc[multi["is_mixed"], "intensity_fold_range"].median())
            if multi["is_mixed"].any() else float("nan"),
    }
    return per_cell, headline


# ---------------------------------------------------------------------------
# 5. Figures
# ---------------------------------------------------------------------------
def fig_intensity_gmm(fit, base_ploidy, path, label="fluorescence intensity"):
    """Histogram of log2(measured value) overlaid with the fitted ploidy peaks."""
    x = fit["x_log2"]
    gmm, k = fit["gmm"], fit["k"]

    fig, ax = plt.subplots(figsize=(7, 4.5))
    ax.hist(x, bins=60, density=True, color="#BBBBBB",
            edgecolor="white", linewidth=0.3, label="all nuclei")

    # Smooth x-grid to draw the model's curves on.
    grid = np.linspace(x.min(), x.max(), 500).reshape(-1, 1)
    total = np.exp(gmm.score_samples(grid))                 # combined fit
    resp = gmm.predict_proba(grid)
    comp = resp * total[:, None]                            # each peak alone

    order = fit["order"]
    for rank, raw in enumerate(order, start=1):             # dim -> bright
        ax.plot(grid.ravel(), comp[:, raw], "--", lw=1.8,
                color=PALETTE[(rank - 1) % len(PALETTE)],
                label=f"class {rank} ({ploidy_label(rank, base_ploidy)})")
    ax.plot(grid.ravel(), total, "k-", lw=2.0, label="combined fit")

    ax.set_xlabel(f"log$_2$( {label} )")
    ax.set_ylabel("density")
    ax.set_title(f"Ploidy classes from {label}  (K = {k}, chosen by BIC)")
    ax.legend(fontsize=8, framealpha=0.9)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_model_selection(fit, path):
    """BIC and AIC vs number of classes, with the chosen K marked."""
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(fit["Ns"], fit["bic"], "o-", color="#EE6677", label="BIC")
    ax.plot(fit["Ns"], fit["aic"], "s--", color="#4477AA", label="AIC")
    kbest = fit["Ns"][int(np.argmin(fit["bic"]))]
    ax.axvline(kbest, color="k", ls=":", lw=1)
    ax.annotate(f"chosen K = {kbest}", xy=(kbest, np.min(fit["bic"])),
                xytext=(6, 12), textcoords="offset points", fontsize=10)
    ax.set_xlabel("number of ploidy classes (K)")
    ax.set_ylabel("information criterion (lower = better)")
    ax.set_title("How many ploidy levels? Model selection")
    ax.legend()
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_class_percentages(df, fit, base_ploidy, path):
    """Bar chart: what % of all nuclei fall in each ploidy class."""
    counts = (df["ploidy_class"].value_counts(normalize=True)
              .sort_index() * 100)
    labels = [f"{c}\n{ploidy_label(c, base_ploidy)}" for c in counts.index]
    colors = [PALETTE[(c - 1) % len(PALETTE)] for c in counts.index]

    fig, ax = plt.subplots(figsize=(6, 4))
    bars = ax.bar(labels, counts.values, color=colors, edgecolor="black",
                  linewidth=0.5)
    ax.bar_label(bars, fmt="%.1f%%", padding=2, fontsize=10)
    ax.set_ylabel("% of nuclei")
    ax.set_xlabel("ploidy class")
    ax.set_title("Ploidy distribution across all nuclei")
    ax.set_ylim(0, counts.max() * 1.18)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_within_cell(per_cell, headline, path, label="fluorescence intensity"):
    """The key figure for the multinucleate question, in two panels."""
    multi = per_cell[per_cell["n_nuclei"] >= 2]
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11, 4.4))

    # Left: how many distinct ploidy levels each cell contains.
    dist_counts = (multi["n_distinct_ploidy"].value_counts(normalize=True)
                   .sort_index() * 100)
    axL.bar([str(i) for i in dist_counts.index], dist_counts.values,
            color=["#228833" if i == 1 else "#EE6677" for i in dist_counts.index],
            edgecolor="black", linewidth=0.5)
    for i, v in zip(range(len(dist_counts)), dist_counts.values):
        axL.text(i, v + 0.8, f"{v:.0f}%", ha="center", fontsize=10)
    axL.set_xlabel("distinct ploidy levels found inside one cell")
    axL.set_ylabel("% of multinucleate cells")
    axL.set_title(f"{headline['pct_mixed_confident']:.0f}% of cells confidently MIXED\n"
                  f"(green = uniform, red = >1 ploidy class)")
    axL.set_ylim(0, max(dist_counts.values) * 1.2)

    # Right: threshold-free check. Brightest/dimmest intensity ratio per cell,
    # split by whether the model called the cell uniform or mixed. Uniform cells
    # cluster near 1 (just noise); mixed cells push toward 2x (a real doubling).
    uni = multi.loc[~multi["is_mixed"], "intensity_fold_range"]
    mix = multi.loc[multi["is_mixed"], "intensity_fold_range"]
    bins = np.linspace(1, max(3.0, multi["intensity_fold_range"].max()), 30)
    axR.hist(uni, bins=bins, alpha=0.7, color="#228833", label="uniform cells")
    axR.hist(mix, bins=bins, alpha=0.7, color="#EE6677", label="mixed cells")
    axR.axvline(2.0, color="k", ls=":", lw=1)
    axR.text(2.02, axR.get_ylim()[1] * 0.88, "2x = one\ndoubling", fontsize=8)
    axR.axvline(headline["fold_threshold"], color="#555555", ls="--", lw=1)
    axR.text(headline["fold_threshold"] + 0.02, axR.get_ylim()[1] * 0.55,
             "mixed-call\ncutoff", fontsize=8, color="#555555")
    axR.set_xlabel(f"max / min {label} of nuclei within a cell")
    axR.set_ylabel("number of cells")
    axR.set_title(f"Within-cell {label} range (no model, no threshold)")
    axR.legend()

    fig.suptitle("Do the nuclei inside a cell share a ploidy?", fontsize=13)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_intensity_vs_volume(df, intensity_col, volume_col, base_ploidy, path):
    """2D sanity check: intensity vs volume, colored by ploidy class."""
    fig, ax = plt.subplots(figsize=(6, 5))
    for c in sorted(df["ploidy_class"].unique()):
        sub = df[df["ploidy_class"] == c]
        ax.scatter(sub[intensity_col], sub[volume_col], s=14, alpha=0.6,
                   color=PALETTE[(c - 1) % len(PALETTE)],
                   label=f"class {c} ({ploidy_label(c, base_ploidy)})")
    ax.set_xscale("log", base=2)
    ax.set_yscale("log", base=2)
    ax.set_xlabel("fluorescence intensity (log$_2$)")
    ax.set_ylabel("nuclear volume (log$_2$)")
    ax.set_title("Intensity vs volume, colored by ploidy class")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_validation(df, base_ploidy, path):
    """If ground truth exists (demo data), show assigned class vs true ploidy."""
    ct = pd.crosstab(df["true_ploidy"], df["ploidy_label"])
    # Order the assigned-ploidy columns numerically (2C,4C,8C,16C), not as text
    # (otherwise '16C' sorts before '2C' and the diagonal looks scrambled).
    ct = ct[sorted(ct.columns, key=lambda s: int(s.rstrip("C")))]
    fig, ax = plt.subplots(figsize=(6, 4.5))
    im = ax.imshow(ct.values, cmap="Blues", aspect="auto")
    ax.set_xticks(range(len(ct.columns)), ct.columns)
    ax.set_yticks(range(len(ct.index)), [f"{p}C" for p in ct.index])
    ax.set_xlabel("ploidy assigned by the pipeline")
    ax.set_ylabel("true ploidy (ground truth)")
    ax.set_title("Validation: assigned vs true ploidy\n(should be a clean diagonal)")
    for i in range(ct.shape[0]):
        for j in range(ct.shape[1]):
            ax.text(j, i, ct.values[i, j], ha="center", va="center",
                    color="black", fontsize=9)
    fig.colorbar(im, ax=ax, label="number of nuclei")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


# ---------------------------------------------------------------------------
# 6. Tie it all together
# ---------------------------------------------------------------------------
def run_one(df, label, args, outdir):
    """Run the whole analysis on one dataframe (one group) and write outputs."""
    print(f"\n=== Analysing: {label}  ({len(df)} nuclei, "
          f"{df[args.cell_col].nunique()} cells) ===")

    fit = fit_ploidy_gmm(df[args.intensity_col].to_numpy(), args)
    df = df.copy()
    df["ploidy_class"] = fit["class_id"]
    df["ploidy_label"] = [ploidy_label(c, args.base_ploidy) for c in fit["class_id"]]

    fold_txt = ", ".join(f"{f:.2f}x" for f in fit["fold_change"])
    print(f"  chosen K (ploidy levels): {fit['k']}")
    print(f"  fold-change between neighbouring classes: {fold_txt}")
    print(f"  (values near 2.0 confirm these are real ploidy doublings)")

    per_cell, headline = within_cell_analysis(
        df, args.cell_col, args.intensity_col, args.mixed_fold_threshold)
    print(f"  multinucleate cells: {headline['n_multinucleate']}")
    print(f"  MIXED by class only            : {headline['n_mixed']} "
          f"({headline['pct_mixed']:.1f}%)")
    print(f"  MIXED confidently (>= {args.mixed_fold_threshold}x gap): "
          f"{headline['n_mixed_confident']} "
          f"({headline['pct_mixed_confident']:.1f}%)  <- report this one")

    # ---- write tables ----
    df.to_csv(os.path.join(outdir, "per_nucleus_classified.csv"), index=False)
    per_cell.to_csv(os.path.join(outdir, "per_cell_summary.csv"), index=False)

    # ---- write the figures ----
    fig_intensity_gmm(fit, args.base_ploidy,
                      os.path.join(outdir, "fig1_intensity_gmm.png"), args.label)
    fig_model_selection(fit, os.path.join(outdir, "fig2_model_selection.png"))
    fig_class_percentages(df, fit, args.base_ploidy,
                          os.path.join(outdir, "fig3_class_percentages.png"))
    # The within-cell figure only makes sense if some cells actually hold >=2
    # nuclei. With --cell-col none every nucleus is its own cell, so we skip it.
    if headline["n_multinucleate"] > 0:
        fig_within_cell(per_cell, headline,
                        os.path.join(outdir, "fig4_within_cell.png"), args.label)
    else:
        print("  (no multinucleate cells -> skipping the within-cell figure)")
    if args.volume_col != "none" and args.volume_col in df.columns:
        fig_intensity_vs_volume(df, args.intensity_col, args.volume_col,
                                args.base_ploidy,
                                os.path.join(outdir, "fig5_intensity_vs_volume.png"))
    if "true_ploidy" in df.columns:
        fig_validation(df, args.base_ploidy,
                       os.path.join(outdir, "fig6_validation.png"))

    # ---- write the plain-text report ----
    write_summary(df, fit, per_cell, headline, args,
                  os.path.join(outdir, "summary.txt"))
    return df, per_cell, headline, fit


def write_summary(df, fit, per_cell, headline, args, path):
    lines = []
    lines.append("PLOIDY PIPELINE - SUMMARY REPORT")
    lines.append("=" * 50)
    lines.append(f"Input file        : {args.csv}")
    lines.append(f"Nuclei analysed   : {len(df)}")
    lines.append(f"Cells analysed    : {df[args.cell_col].nunique()}")
    lines.append("")
    lines.append("PLOIDY CLASSES (from the Gaussian Mixture Model)")
    lines.append("-" * 50)
    lines.append(f"Number of classes chosen by BIC : {fit['k']}")
    for c in range(1, fit["k"] + 1):
        n = int((df["ploidy_class"] == c).sum())
        pct = 100.0 * n / len(df)
        lines.append(f"  class {c} ({ploidy_label(c, args.base_ploidy):>4}): "
                     f"{n:5d} nuclei ({pct:5.1f}%)   "
                     f"mean intensity = {fit['means_real'][c-1]:.1f}")
    fold_txt = ", ".join(f"{f:.2f}x" for f in fit["fold_change"])
    lines.append(f"Fold-change between neighbouring classes: {fold_txt}")
    lines.append("  (near 2.0 => the classes really are ploidy doublings)")
    lines.append("")
    lines.append("WITHIN-CELL PLOIDY (your multinucleate question)")
    lines.append("-" * 50)
    lines.append(f"Multinucleate cells (>=2 nuclei) : {headline['n_multinucleate']}")
    lines.append(f"  mixed by ploidy class alone     : {headline['n_mixed']} "
                 f"({headline['pct_mixed']:.1f}%)")
    lines.append(f"  mixed AND >= {headline['fold_threshold']}x intensity gap : "
                 f"{headline['n_mixed_confident']} "
                 f"({headline['pct_mixed_confident']:.1f}%)  <-- headline number")
    lines.append("  (the second, stricter count ignores nuclei that only just")
    lines.append("   crossed a class boundary because of measurement noise.)")
    lines.append(f"Median brightest/dimmest ratio, uniform cells: "
                 f"{headline['median_fold_uniform']:.2f}  (near 1 = no real gap)")
    lines.append(f"Median brightest/dimmest ratio, mixed cells  : "
                 f"{headline['median_fold_mixed']:.2f}  (near/above 2 = a doubling)")
    if "true_ploidy" in df.columns:
        acc = (df["ploidy_label"].str.rstrip("C").astype(int)
               == df["true_ploidy"]).mean() * 100
        lines.append("")
        lines.append("VALIDATION (demo data only)")
        lines.append("-" * 50)
        lines.append(f"Per-nucleus ploidy called correctly: {acc:.1f}%")
    text = "\n".join(lines)
    with open(path, "w") as fh:
        fh.write(text + "\n")
    print("\n" + text)


def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    df = load_data(args)

    print(textwrap.dedent(f"""
    Loaded {len(df)} nuclei from {args.csv}
      intensity column : {args.intensity_col}
      cell column      : {args.cell_col}
      volume column    : {args.volume_col}
    """).rstrip())

    # If a group column was given, analyse each group into its own subfolder.
    if args.group_col != "none" and args.group_col in df.columns:
        for g, sub in df.groupby(args.group_col):
            sub_out = os.path.join(args.outdir, f"group_{g}")
            os.makedirs(sub_out, exist_ok=True)
            run_one(sub, str(g), args, sub_out)
    else:
        run_one(df, "all data", args, args.outdir)

    print(f"\nDone. Open the '{args.outdir}/' folder for figures and tables.")


if __name__ == "__main__":
    main()
